### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by mrl893** [zedtux/ror-refactor#3]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.3
**Thrown From**: [ror-refactor](https://github.com/zedtux/ror-refactor) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/rm/.atom/packages/ror-refactor/lib/tools/extract-code.js:114

TypeError: Cannot read property '1' of undefined
    at ExtractCode.extractMethodOrLine (/packages/ror-refactor/lib/tools/extract-code.js:114:19)
    at ExtractCode.refactor (/packages/ror-refactor/lib/tools/extract-code.js:49:14)
    at HTMLElement.rorRefactorExtractCode (/packages/ror-refactor/lib/ror-refactor.js:18:59)
    at CommandRegistry.handleCommandEvent (/private/var/folders/9s/y8_06b491lzbzbg0b5knwf2c0000gn/T/AppTranslocation/45A6782E-F268-4A4D-8F74-35FF2AA36226/d/Atom.app/Contents/Resources/app/static/<embedded>:11:352694)
    at CommandRegistry.dispatch (/private/var/folders/9s/y8_06b491lzbzbg0b5knwf2c0000gn/T/AppTranslocation/45A6782E-F268-4A4D-8F74-35FF2AA36226/d/Atom.app/Contents/Resources/app/static/<embedded>:11:351169)
    at AtomEnvironment.dispatchContextMenuCommand (/private/var/folders/9s/y8_06b491lzbzbg0b5knwf2c0000gn/T/AppTranslocation/45A6782E-F268-4A4D-8F74-35FF2AA36226/d/Atom.app/Contents/Resources/app/static/<embedded>:1:786983)
    at EventEmitter.t (/private/var/folders/9s/y8_06b491lzbzbg0b5knwf2c0000gn/T/AppTranslocation/45A6782E-F268-4A4D-8F74-35FF2AA36226/d/Atom.app/Contents/Resources/app/static/<embedded>:1:795037)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
  7x -3:20.2.0 core:move-left (input.hidden-input)
  3x -3:16.8.0 core:move-right (input.hidden-input)
     -3:16.1.0 core:backspace (input.hidden-input)
  2x -3:15.6.0 core:move-left (input.hidden-input)
  2x -3:11.1.0 core:move-right (input.hidden-input)
     -3:10.2.0 core:backspace (input.hidden-input)
  5x -3:07.5.0 core:move-right (input.hidden-input)
  6x -3:05.8.0 core:backspace (input.hidden-input)
  6x -3:01.6.0 core:move-left (input.hidden-input)
     -2:56.3.0 autocomplete-plus:confirm (input.hidden-input)
  2x -2:53.7.0 core:save (input.hidden-input)
     -0:46.9.0 editor:newline (input.hidden-input)
  6x -0:40.4.0 core:move-left (input.hidden-input)
     -0:37.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:36.2.0 core:save (input.hidden-input)
     -0:04.1.0 ror-refactor:extract-code (span.syntax--keyword.syntax--operator.syntax--js)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.16.3 
js-refactor 0.8.1 
platformio-ide-terminal 2.10.1 
react 0.18.0 
react-autocomplete 1.2.0 
react-redux-react-native-snippets 0.2.4 
react-snippets 2.0.0 
ror-refactor 0.3.1 
teletype 0.13.4 
```

**Comment by zedtux** [comment]
No step to reproduce ... and I'm not using it in those days, not sure I can work on that one. Feel free to submit a PR.
